### PR TITLE
Update msgpack & bump version.

### LINKED ISSUE #60: Fails to build with Node v4.1.0
The problem seems related to the `msgpack` module. I've opened an issue there too:
https://github.com/msgpack/msgpack-node/issues/27

```
npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/Cellar/nvm/versions/node/v4.1.0/bin/node" "/usr/local/Cellar/nvm/versions/node/v4.1.0/bin/npm" "install" "zerorpc"
npm ERR! node v4.1.0
npm ERR! npm  v2.14.3
npm ERR! code ELIFECYCLE

npm ERR! msgpack@0.2.6 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the msgpack@0.2.6 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the msgpack package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls msgpack
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/Ale/Dropbox/Docs/Good Karma/Projects/Distilled/code/back/koa/npm-debug.log
```

What worries me a bit, looking at the other `msgpack` issues is that the build seems to fail on many Node versions: https://github.com/msgpack/msgpack-node/issues/

Should this module be swapped for another Node JS version of msgpak, or be substituted entirely with `JSON.stringify` and `JSON.parse`? The latter would produce slightly longer strings, but should be way faster with current implementation (as mentioned in [`msgpack-node` docs](https://github.com/msgpack/msgpack-node/blob/master/README.md)).

### PR DESCRIPTION
**Pull request by zachizi**
Fixes #60

### CODE REVIEW

**Comment by zachizi** [comment]
So… it has occurred to me that msgpack-0.2.x isn't going to work on node-4.x.x and msgpack-1.0.0 isn't going to work on node-0.12.  The solution to that is beyond me.  Leaving this here for now.  Noting it was suggested we drop msgpack in #60.

**Comment by zachizi** [comment]
Issue for Node < 4 support here https://github.com/msgpack/msgpack-node/issues/28

**Comment by bombela** [comment]
Do we really need to be compatible with node-0.12? I mean how far back do we need to be realistically compatible with?

**Comment by zachizi** [comment]
I think I would consider node's [LTS plan](https://github.com/nodejs/LTS) (0.12 is supposed to be supported 6 months past the October v4 LTS release) and the fact that there are still a few packages here and there which still do not support node-4.x.x.  The nan package is supposed to take away these compatibility issues but there are still problems building msgpack on 0.12 that could probably be fixed.  Would be curious to see if msgpack/msgpack-node#28 gets resolved quickly.

**Comment by bombela** [comment]
Ah thanks for the details. I was not aware of the node + io.js fork followed by the merge to 4.0.

**Comment by bombela** [comment]
Thanks! I will bump and release a new version on npm this week.

**Comment by zachizi** [comment]
Thank _you_.

**Pull request merged**
